version: '3'
services:
  www:
    build:
      context: ./nginx
      args:
        - "VERSION=${NGINX_VERSION}"
        - "SITEPATH=${SITEPATH}"
    volumes:
      - "./config:/etc/nginx/conf.d"
      - "./www:${SITEPATH}"
    depends_on:
      - db
      - php
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    working_dir: "${SITEPATH}"
  php:
    build:
      context: ./phpfpm
      args:
        - "VERSION=${PHP_VERSION}"
    volumes:
      - "./www:${SITEPATH}"
    working_dir: "${SITEPATH}"
  db:
    image: "mariadb:${MYSQL_MARIADB_VERSION}"
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: unless-stopped
    environment:
    - "MYSQL_DATABASE=${MYSQL_DBNAME}"
    - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOTPWD}"
    - "MYSQL_USER=${MYSQL_USER}"
    - "MYSQL_PASSWORD=${MYSQL_PWD}"

